### ISSUE TITLE
getDialogIndex()

### ISSUE THREAD

**Issue by konstantinschuette** [SAMP-UDF/SAMP-UDF-for-AutoHotKey#5]
`index := readMem(hGTA, dwPointer + SAMP_DIALOG_INDEX_OFFSET, 4, "int")`

ist ein integer

**Comment by Suchty112** [comment]
Ist zumindest erstmal in der Dev-Version R17 für die "neue" SAMP Version drinne...

**Comment by Serray** [comment]
Funktioniert derzeit nicht. Der Wert bleibt immer auf 1
